// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://ocwoqhnxaunhrezvsevn.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Im9jd29xaG54YXVuaHJlenZzZXZuIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDU4MzUwOTEsImV4cCI6MjA2MTQxMTA5MX0.IyTxH0R6yC0sMR7CUDl9RDFlmmaCOQQ-pe17s1VblQs";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);